server:
  port: 10010
spring:
  application:
    name: esdemo
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://10.253.50.250:3306/yunce?useSSL=false&allowMultiQueries=true
    password: 1qaz2WSX!@
    username: zzyq
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name:  com.mysql.jdbc.Driver
logging:
  level.root: warn
common:
  es:
    types:
      ES_DATA_TYPE: data
      ES_USER_TYPE: user
      ES_TASK_TYPE: task
    hosts: http://10.253.90.84:9200
    indexs:
      YUNCEDATAES: yunce_data_es
      ES_INDEX: yunce_data
      YUNCEORIGINAL: yunce_original
      ES_TASK_DATA_INDEX: yunce_task_data
      ES_TASK_DATA_V2_INDEX: yunce_task_data_v3
    enabled: true
    cluster-name: my-test
    port: 9200
swagger:
  config:
    pack-location:  zxx