server:
  port: 10010
spring:
  application:
    name: esdemo
  redis:
    host: 127.0.0.1
    port: 6379
  #  datasource:
  #    url: jdbc:mysql://10.253.50.250:3306/yunce?useSSL=false&allowMultiQueries=true
  #    password: 1qaz2WSX!@
  #    username: zzyq
  #    type: com.zaxxer.hikari.HikariDataSource
  #    driver-class-name:  com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-name:  my-test
      cluster-nodes: 10.253.90.84:930,10.253.90.90:9300,10.253.90.93:9300
logging:
  level.root: warn
common:
  es:
    types:
      ES_DATA_TYPE: data
      ES_USER_TYPE: user
      ES_TASK_TYPE: task
    hosts: http://10.253.90.84:9200
    indexs:
      YUNCEDATAES: yunce_data_es
      ES_INDEX: yunce_data
      YUNCEORIGINAL: yunce_original
      ES_TASK_DATA_INDEX: yunce_task_data
      ES_TASK_DATA_V2_INDEX: myyunce
    enabled: true
    cluster-name: my-test
    port: 9200
  custom-durid:
    enabled: true
    driverClassName: com.mysql.jdbc.Driver
    # 250
    url: jdbc:mysql://10.253.50.250:3306/yunce?useSSL=false&allowMultiQueries=true
    username: zzyq
    password: 1qaz2WSX!@
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 50
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: "SELECT 1 FROM DUAL"
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    filters: "stat,wall,log4j"
swagger:
  config:
    pack-location:  zxx